/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.donarsWorkArea;

import businesslogic.EcoSystem;
import businesslogic.User;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author manojreddy
 */
public class DonorHomeJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessJPanel;
    private EcoSystem ecoSystem;
    private User userLogged;
        
    
    /**
     * Creates new form DonorHomeJPanel
     */
    public DonorHomeJPanel(JPanel userProcessJPanel, EcoSystem ecoSystem, User userLogged) {
        initComponents();
        
        this.userProcessJPanel = userProcessJPanel;
        this.ecoSystem = ecoSystem;
        this.userLogged = userLogged;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        btnupdatemyprofile = new javax.swing.JButton();
        btnmanagemydonations = new javax.swing.JButton();

        setLayout(null);

        lbltitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltitle.setText("Donor Home Page");
        add(lbltitle);
        lbltitle.setBounds(192, 13, 174, 27);

        btnupdatemyprofile.setText("Update my Profile");
        btnupdatemyprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatemyprofileActionPerformed(evt);
            }
        });
        add(btnupdatemyprofile);
        btnupdatemyprofile.setBounds(62, 101, 133, 25);

        btnmanagemydonations.setText("Manage My Donations");
        btnmanagemydonations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanagemydonationsActionPerformed(evt);
            }
        });
        add(btnmanagemydonations);
        btnmanagemydonations.setBounds(366, 101, 157, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdatemyprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatemyprofileActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.add("UpdateDonorProfileJPanel", new UpdateDonorProfileJPanel(userProcessJPanel,ecoSystem,userLogged));
        cardLayout.next(userProcessJPanel);
    }//GEN-LAST:event_btnupdatemyprofileActionPerformed

    private void btnmanagemydonationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanagemydonationsActionPerformed
        CardLayout cardLayout = (CardLayout) userProcessJPanel.getLayout();
        userProcessJPanel.add("ManageMyDonationsJPanel", new ManageMyDonationsJPanel(userProcessJPanel,ecoSystem,userLogged));
        cardLayout.next(userProcessJPanel);
    }//GEN-LAST:event_btnmanagemydonationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmanagemydonations;
    private javax.swing.JButton btnupdatemyprofile;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
