/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.donarsWorkArea;

import userinterface.systemAdminsWorkArea.*;
import businesslogic.CityName;
import businesslogic.CityNetwork;
import businesslogic.EcoSystem;
import businesslogic.User;
import businesslogic.donor.Donation;
import businesslogic.donor.Donor;
import businesslogic.enums.Category;
import businesslogic.sysAdmin.SysAdmin;
import java.awt.CardLayout;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manojreddy
 */
public class ManageMyDonationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminHomeJPanel
     */
    
    private JPanel userProcessJpanel;
    private EcoSystem ecoSystem;
    private User userLogged;
    private Donor donor;
    
    public ManageMyDonationsJPanel(JPanel userProcessJpanel, EcoSystem ecoSystem, User userLogged) {
        initComponents();
        this.userProcessJpanel = userProcessJpanel;
        this.ecoSystem = ecoSystem;
        this.userLogged = userLogged;
        this.donor = (Donor) userLogged;
        populateCategories();
        populateCities();
        populateDonationHistoryTable();
    }
    
    public void populateCategories() {
        
        donationcategoryjComboBox.removeAllItems();
        String[] categories = Category.getCategoriesArray();
        for(String category:categories) {
            donationcategoryjComboBox.addItem(category);
        }
    }
    
    public void populateCities() {
        
        List<CityNetwork> cityNetworks = ecoSystem.getCityNetworkDirectory().getCityNetworks();
        cityjComboBox.removeAllItems();
        for(CityNetwork cityNetwork:ecoSystem.getCityNetworkDirectory().getCityNetworks()) {
            cityjComboBox.addItem(cityNetwork.getCityName().name());
        }
    }
    
    public void populateDonationHistoryTable() {
        
//        int selectedIndex = donationcategoryjComboBox.getSelectedIndex();
//        if(selectedIndex<0) {
//            JOptionPane.showMessageDialog(this, "Please select a category to proceed further");
//            return;
//        }
//        
//        int selectedIndex2 = cityjComboBox.getSelectedIndex();
//        if(selectedIndex2<0) {
//            JOptionPane.showMessageDialog(this, "Please select a city to proceed further");
//            return;
//        }
        
        DefaultTableModel donationHistory = (DefaultTableModel) tbldonationHistory.getModel();
        donationHistory.setRowCount(0);
        
        int donationsCount=0;
        for(Donation donation:donor.getDonations()) {
            if (donation.getCategory().name().equalsIgnoreCase((String) donationcategoryjComboBox.getSelectedItem()) 
                    && donation.getCityNetwork().getCityName().name().equalsIgnoreCase((String) cityjComboBox.getSelectedItem())){
            donationsCount++;
            Object[] row = new Object[7];
            row[0]=donationsCount;
            row[1]=donation;
            row[2]=donation.getInformation();
            row[3]=donation.getUsageStatus();
            row[4]=donation.getOrganization();
            row[5]=donation.getDeliveryVolunteer().getName();
            row[6]=donation.getDonationStatus();
            
            donationHistory.addRow(row);
            }
        }
        countTotaljLabel.setText(String.valueOf(donationsCount));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerjLabel = new javax.swing.JLabel();
        donationcategoryjComboBox = new javax.swing.JComboBox<>();
        btnmakenewdonation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldonationHistory = new javax.swing.JTable();
        countTotaljLabel = new javax.swing.JLabel();
        countLablejLabel = new javax.swing.JLabel();
        lbldonationCategory = new javax.swing.JLabel();
        cityjComboBox = new javax.swing.JComboBox<>();
        lbldonationCategory1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        headerjLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        headerjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerjLabel.setText("Please Select a Donation Category");
        add(headerjLabel);
        headerjLabel.setBounds(340, 20, 310, 34);

        donationcategoryjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationcategoryjComboBoxActionPerformed(evt);
            }
        });
        add(donationcategoryjComboBox);
        donationcategoryjComboBox.setBounds(20, 160, 224, 22);

        btnmakenewdonation.setText("Make New Donation >>");
        btnmakenewdonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmakenewdonationActionPerformed(evt);
            }
        });
        add(btnmakenewdonation);
        btnmakenewdonation.setBounds(780, 600, 180, 25);

        tbldonationHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "S.No", "Donor", "Information", "Usage Status", "Organization", "Delivery Volunteer", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbldonationHistory);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 950, 170);

        countTotaljLabel.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        countTotaljLabel.setText("0");
        add(countTotaljLabel);
        countTotaljLabel.setBounds(70, 520, 7, 18);

        countLablejLabel.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        countLablejLabel.setText("Count :");
        add(countLablejLabel);
        countLablejLabel.setBounds(20, 520, 45, 18);

        lbldonationCategory.setText("City:");
        add(lbldonationCategory);
        lbldonationCategory.setBounds(320, 130, 40, 20);

        cityjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityjComboBoxActionPerformed(evt);
            }
        });
        add(cityjComboBox);
        cityjComboBox.setBounds(320, 160, 224, 22);

        lbldonationCategory1.setText("Donation Category:");
        add(lbldonationCategory1);
        lbldonationCategory1.setBounds(20, 130, 120, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Donation History");
        add(jLabel1);
        jLabel1.setBounds(390, 240, 160, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmakenewdonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmakenewdonationActionPerformed
//        int selectedIndex = donationcategoryjComboBox.getSelectedIndex();
//        if(selectedIndex<0) {
//            JOptionPane.showMessageDialog(this, "Please add a city to proceed further");
//            return;
//        }
        
        CardLayout cardLayout = (CardLayout) userProcessJpanel.getLayout();
        userProcessJpanel.add("MakeNewDonationJPanel",new MakeNewDonationJPanel(userProcessJpanel,ecoSystem, userLogged));
        cardLayout.next(userProcessJpanel);
    }//GEN-LAST:event_btnmakenewdonationActionPerformed

    private void donationcategoryjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationcategoryjComboBoxActionPerformed
        populateDonationHistoryTable();
    }//GEN-LAST:event_donationcategoryjComboBoxActionPerformed

    private void cityjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityjComboBoxActionPerformed
        populateDonationHistoryTable();
    }//GEN-LAST:event_cityjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmakenewdonation;
    private javax.swing.JComboBox<String> cityjComboBox;
    private javax.swing.JLabel countLablejLabel;
    private javax.swing.JLabel countTotaljLabel;
    private javax.swing.JComboBox<String> donationcategoryjComboBox;
    private javax.swing.JLabel headerjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldonationCategory;
    private javax.swing.JLabel lbldonationCategory1;
    private javax.swing.JTable tbldonationHistory;
    // End of variables declaration//GEN-END:variables
}
